### ISSUE TITLE
[User-Story]: replacements

### ISSUE THREAD

**Issue by hayone1** [hayone1/MongoPrismSync#10]
### As a...

**As a** user
**I need** a replacement feature
**So that** copy values from one document into another document.

### Acceptance criteria (optional)

```gherkin
Given [some context]
When [certain action is taken]
Then [the outcome of action is observed]
```

### Assumptions and Requirements (optional)

* There should be a postRenderers[].kustomize.replacements field similar to kpt (kustomize replacements)[https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/] in the weaveconfig.yml. eg:
```
render:
  env_name:
    postRenderers:
      - kustomize:
          replacements:
            - path: my-replacement.yaml
            - source:
                kind: Secret
                name: my-secret
              targets:
              - select:
                  name: hello
                  kind: Job
                fieldPaths:
                - spec.template.spec.containers.[name=hello].env.[name=SECRET_TOKEN].value
```
* There is also an issue raised in fluxcd for this feature. See (here)[https://github.com/fluxcd/helm-controller/issues/496].
* There should be a feature to directly use scalar, object and list values as the source data as seen in (this issue)[https://github.com/kubernetes-sigs/kustomize/issues/5516].

### Impact (optional)

High

### Version

0.0.1 (Latest)
