### ISSUE TITLE
[User-Story]: weave (json-patch)

### ISSUE THREAD

**Issue by hayone1** [hayone1/MongoPrismSync#4]
### As a...

**As a** mongocd user
**I need** a declearative customization feature
**So that** customize my documents before pushing them to the destination database.

### Acceptance criteria (optional)

```gherkin
Given I have configured json patch in my weave.yml
When I run the weave command
Then I should see a list of updates that will be applied to my destination db and should be able to accept or deny them.
```

### Assumptions and Requirements (optional)

* There should be a patch post-render node similar to fluxcd helm post-render in the weaveconfig.yml. eg:
``` yaml
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: metrics-server
            patch: |
              - op: add
                path: /metadata/labels/environment
                value: production
```
* prioritized targets will be `database` and `collection`. Any other target will be searched for in the documents fields to further narrow the filter after the priority targets have been considered. 
* If `database` and `collection` targets are not specified, then a direct search within the documents will be made. This could affect performance. 
* valid targets can be regex just like in fluxcd customize.
* The weave command shall create a `base` folder which will contain the database folder, collection folder and document json data as it is in the source database.
* The weave command shall create an `overlay` folder which will also contain the database folder, collection folder and document json data, but with the patches applied.
* The weave command will print a list of diffs(presented as patch operations) between the documents data in the overlay folder and the output folder.
* The weave command will allow user to choose or reject to apply the diffs.
* There should also be an option to keep or delete the base and overlay folder. This should be represented in the weaveconfig,yml 

### Impact (optional)

High

### Version

0.0.1 (Latest)
